name: Check Python Shebang

on: [push]

jobs:
  check_python_shebang:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Choose your Python version

      # Step 3: Check whether the python bash is present in all .py files
      - name: Check whether the python bash is present in all .py files
        run: |
          python ./.github/workflows/check_python_shebang.py borb/
