name: Check Visibility Markers

on: [push]

jobs:
  check_visibility_markers:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Retrieve the latest code version
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up the required Python version
      - name: Configure Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the target Python version

      # Step 3: Check for visibility markers (CONSTRUCTOR / PRIVATE / PUBLIC) in code files
      - name: Check Visibility Markers in Code Files
        run: |
          python ./.github/workflows/check_visibility_markers.py borb/
