name: Check Init Files

on: [push]

jobs:
  check_init_files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Choose your Python version

      # Step 3: Check whether the __init__.py files are not empty
      - name: Check whether the __init__.py files are not empty
        run: |
          python ./.github/workflows/check_init_files.py .
