name: Check ConformanceCheck order

on: [push]

jobs:
  check_conformance_check_order:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Choose your Python version

      # Step 3: Check whether the conformance_checks.py file is sorted
      - name: Check whether the ConformanceChecks are sorted
        run: |
          python ./.github/workflows/check_conformance_check_order.py borb/
